Dev
q7ice/Todo pull request #1
Opened 2021-06-22 07:34 UTC by q7ice

2021-07-03 13:51 UTC, andrewzenkov commented
![2021-07-03 16 51 082](https://user-images.githubusercontent.com/81105315/124356487-e4c24a80-dc1e-11eb-9081-3470d3801f38.jpg)

It needs to be fixed since we have not soft ui if there a lot of tasks

2021-07-03 14:08 UTC, andrewzenkov requested changes

2021-07-03 14:08 UTC, andrewzenkov commented on src/components/Filter/Filter.jsx
> +import React from "react";
Forgot to make export in Filter/index.js (now it's empty file )

2021-07-03 14:08 UTC, andrewzenkov commented on src/components/App/todoSlice.js
> +          return todo;
I would recommend don't handle Id of todos as index or something like that.
Please, use library to generate random id and set if for todos once.

It's always bad to change ids during application working

2021-07-03 14:08 UTC, andrewzenkov commented on src/components/InputTodo/InputTodo.jsx
> +        }}
In variables as I mentioned

2021-07-03 14:08 UTC, andrewzenkov commented on src/components/App/todoSlice.js
> +      obj.done = false;
I would recommend to use Model for any entity
at least you can set up exact field you need to fill and set up as fully separated entity but not an usual object

```
      const todo = new Todo({
        id: state.todos.length,
        text: action.payload,
        done: false
      });

      state.todos.push(obj);
```

2021-07-03 14:22 UTC, q7ice commented on src/components/App/todoSlice.js
> +          return todo;
Which libraries would you recommend for such things?

2021-07-03 14:22 UTC, q7ice commented on src/components/App/todoSlice.js
> +      obj.done = false;
Yeah, I found out about this after reading the style guide from "Airbnb", but didn't change the project

2021-07-03 14:27 UTC, q7ice commented on src/components/TodoItem/TodoItem.jsx
> +        onClick={() => dispatch(toggleDone(todoId))}
Did you mean that I need to move this code "() => dispatch(toggleDone(todoId))" to variable or I didn't understand you?

2021-07-03 14:34 UTC, q7ice commented on src/components/TodoItem/TodoItem.jsx
> +      <div className={done ? "todo-done" : null}>{text}</div>
Do I need to move this {done ? "todo-done" : null} to new variable?

2021-07-03 14:36 UTC, q7ice commented on src/components/App/todoSlice.js
> +import { createSlice } from "@reduxjs/toolkit";
I will use that next time, just didn't know it then :)

2021-07-03 14:37 UTC, q7ice commented on src/components/Filter/Filter.jsx
> +import React from "react";
Oops

2021-07-03 14:42 UTC, q7ice commented
> ![2021-07-03 16 51 082](https://user-images.githubusercontent.com/81105315/124356487-e4c24a80-dc1e-11eb-9081-3470d3801f38.jpg)
> 
> It needs to be fixed since we have not soft ui if there are a lot of tasks

I noticed that problem while was developing App, but I forgot to fix that after work. I can put all the "TODOS" in a smaller container, which will have a height lower than the input Todo to fix this problem.

2021-07-03 14:47 UTC, andrewzenkov commented on src/components/TodoItem/TodoItem.jsx
> +        onClick={() => dispatch(toggleDone(todoId))}
Exactly

2021-07-03 14:47 UTC, andrewzenkov commented on src/components/TodoItem/TodoItem.jsx
> +      <div className={done ? "todo-done" : null}>{text}</div>
No, please check 'classnames' library

2021-07-03 14:49 UTC, andrewzenkov commented on src/components/App/todoSlice.js
> +          return todo;
1) you can use reselect
2) but at least you can just move it in selector

2021-07-10 19:00 UTC, andrewzenkov approved these changes

2021-07-10 19:01 UTC, merged